/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as CollegesIndexRouteImport } from './routes/colleges.index'
import { Route as CollegesSlugRouteImport } from './routes/colleges.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIndexRoute = CollegesIndexRouteImport.update({
  id: '/colleges/',
  path: '/colleges/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesSlugRoute = CollegesSlugRouteImport.update({
  id: '/colleges/$slug',
  path: '/colleges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/research': typeof ResearchRoute
  '/student-life': typeof StudentLifeRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/colleges/': typeof CollegesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/research': typeof ResearchRoute
  '/student-life': typeof StudentLifeRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/colleges': typeof CollegesIndexRoute
  '/news': typeof NewsIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/research': typeof ResearchRoute
  '/student-life': typeof StudentLifeRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/colleges/': typeof CollegesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission'
    | '/research'
    | '/student-life'
    | '/colleges/$slug'
    | '/news/$slug'
    | '/programs/$slug'
    | '/colleges/'
    | '/news/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/research'
    | '/student-life'
    | '/colleges/$slug'
    | '/news/$slug'
    | '/programs/$slug'
    | '/colleges'
    | '/news'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admission'
    | '/research'
    | '/student-life'
    | '/colleges/$slug'
    | '/news/$slug'
    | '/programs/$slug'
    | '/colleges/'
    | '/news/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  ResearchRoute: typeof ResearchRoute
  StudentLifeRoute: typeof StudentLifeRoute
  CollegesSlugRoute: typeof CollegesSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  CollegesIndexRoute: typeof CollegesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/': {
      id: '/colleges/'
      path: '/colleges'
      fullPath: '/colleges/'
      preLoaderRoute: typeof CollegesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$slug': {
      id: '/colleges/$slug'
      path: '/colleges/$slug'
      fullPath: '/colleges/$slug'
      preLoaderRoute: typeof CollegesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  ResearchRoute: ResearchRoute,
  StudentLifeRoute: StudentLifeRoute,
  CollegesSlugRoute: CollegesSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  CollegesIndexRoute: CollegesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
